"""Add Digital Twin physics to Motorcycle

Revision ID: 4c389127361b
Revises: 
Create Date: 2026-04-16 17:25:42.779938
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c389127361b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_leaderboard_period'), table_name='leaderboard_cache')
    op.drop_table('leaderboard_cache')
    op.alter_column('communities', 'type',
               existing_type=postgresql.ENUM('brand', 'style', 'region', 'interest', 'event', name='community_type'),
               type_=sa.Enum('BRAND', 'STYLE', 'REGION', 'INTEREST', 'EVENT', name='communitytype'),
               existing_nullable=False)
    op.drop_constraint(op.f('communities_slug_key'), 'communities', type_='unique')
    op.drop_index(op.f('idx_communities_brand'), table_name='communities')
    op.drop_index(op.f('idx_communities_slug'), table_name='communities')
    op.drop_index(op.f('idx_communities_type'), table_name='communities')
    op.create_index(op.f('ix_communities_slug'), 'communities', ['slug'], unique=True)
    op.alter_column('community_memberships', 'role',
               existing_type=postgresql.ENUM('member', 'moderator', 'admin', 'owner', name='membership_role'),
               type_=sa.Enum('MEMBER', 'MODERATOR', 'ADMIN', 'OWNER', name='membershiprole'),
               existing_nullable=True,
               existing_server_default=sa.text("'member'::membership_role"))
    op.drop_index(op.f('idx_memberships_community'), table_name='community_memberships')
    op.drop_index(op.f('idx_memberships_user'), table_name='community_memberships')
    op.create_index(op.f('ix_community_memberships_community_id'), 'community_memberships', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_memberships_user_id'), 'community_memberships', ['user_id'], unique=False)
    op.alter_column('community_posts', 'type',
               existing_type=postgresql.ENUM('discussion', 'question', 'help_request', 'help_offer', 'ride_invite', 'event', 'photo', 'route_share', name='post_type'),
               type_=sa.Enum('DISCUSSION', 'QUESTION', 'HELP_REQUEST', 'HELP_OFFER', 'RIDE_INVITE', 'EVENT', 'PHOTO', 'ROUTE_SHARE', name='posttype'),
               existing_nullable=True,
               existing_server_default=sa.text("'discussion'::post_type"))
    op.drop_index(op.f('idx_posts_author'), table_name='community_posts')
    op.drop_index(op.f('idx_posts_community'), table_name='community_posts')
    op.drop_index(op.f('idx_posts_created'), table_name='community_posts')
    op.drop_index(op.f('idx_posts_type'), table_name='community_posts')
    op.create_index(op.f('ix_community_posts_author_id'), 'community_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_posts_community_id'), 'community_posts', ['community_id'], unique=False)
    op.add_column('motorcycles', sa.Column('weight_kg', sa.Integer(), nullable=True))
    op.add_column('motorcycles', sa.Column('torque_nm', sa.Integer(), nullable=True))
    op.add_column('motorcycles', sa.Column('tire_type', sa.String(length=50), nullable=True))
    op.alter_column('motorcycles', 'type',
               existing_type=postgresql.ENUM('naked', 'sport', 'touring', 'adventure', 'cruiser', 'scooter', 'classic', 'dual_sport', 'enduro', 'supermoto', 'cafe_racer', 'bobber', name='motorcycle_type'),
               type_=sa.Enum('NAKED', 'SPORT', 'TOURING', 'ADVENTURE', 'CRUISER', 'SCOOTER', 'CLASSIC', 'DUAL_SPORT', 'ENDURO', 'SUPERMOTO', 'CAFE_RACER', 'BOBBER', name='motorcycletype'),
               existing_nullable=False)
    op.drop_index(op.f('idx_motorcycles_brand'), table_name='motorcycles')
    op.drop_index(op.f('idx_motorcycles_type'), table_name='motorcycles')
    op.drop_index(op.f('idx_motorcycles_user_id'), table_name='motorcycles')
    op.create_index(op.f('ix_motorcycles_brand'), 'motorcycles', ['brand'], unique=False)
    op.create_index(op.f('ix_motorcycles_user_id'), 'motorcycles', ['user_id'], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=postgresql.ENUM('badge_earned', 'level_up', 'streak', 'challenge_complete', 'report_verified', 'report_near_route', 'community_post', 'community_reply', 'community_mention', 'help_request_nearby', 'system', name='notification_type'),
               type_=sa.Enum('BADGE_EARNED', 'LEVEL_UP', 'STREAK', 'CHALLENGE_COMPLETE', 'REPORT_VERIFIED', 'REPORT_NEAR_ROUTE', 'COMMUNITY_POST', 'COMMUNITY_REPLY', 'COMMUNITY_MENTION', 'HELP_REQUEST_NEARBY', 'SYSTEM', name='notificationtype'),
               existing_nullable=False)
    op.drop_index(op.f('idx_notifications_user'), table_name='notifications')
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_index(op.f('idx_transactions_date'), table_name='point_transactions')
    op.drop_index(op.f('idx_transactions_user'), table_name='point_transactions')
    op.create_index(op.f('ix_point_transactions_user_id'), 'point_transactions', ['user_id'], unique=False)
    op.drop_index(op.f('idx_comments_parent'), table_name='post_comments')
    op.drop_index(op.f('idx_comments_post'), table_name='post_comments')
    op.create_index(op.f('ix_post_comments_parent_id'), 'post_comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_post_comments_post_id'), 'post_comments', ['post_id'], unique=False)
    op.drop_index(op.f('idx_push_tokens_user'), table_name='push_tokens')
    op.create_index(op.f('ix_push_tokens_user_id'), 'push_tokens', ['user_id'], unique=False)
    op.drop_index(op.f('idx_votes_report'), table_name='report_votes')
    op.drop_index(op.f('idx_votes_user'), table_name='report_votes')
    op.create_index(op.f('ix_report_votes_report_id'), 'report_votes', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_votes_user_id'), 'report_votes', ['user_id'], unique=False)
    op.alter_column('road_reports', 'category',
               existing_type=postgresql.ENUM('hazard', 'surface', 'traffic', 'poi', name='report_category'),
               type_=sa.Enum('HAZARD', 'SURFACE', 'TRAFFIC', 'POI', name='reportcategory'),
               existing_nullable=False)
    op.alter_column('road_reports', 'type',
               existing_type=postgresql.ENUM('oil_spill', 'debris', 'pothole', 'construction', 'traffic_light', 'electrical', 'wet', 'ice', 'fog', 'sand', 'leaves', 'heavy_traffic', 'accident', 'police', 'road_closure', 'gas_station', 'moto_shop', 'parking', 'scenic', 'cafe', name='report_type'),
               type_=sa.Enum('OIL_SPILL', 'DEBRIS', 'POTHOLE', 'CONSTRUCTION', 'TRAFFIC_LIGHT', 'ELECTRICAL', 'WET', 'ICE', 'FOG', 'SAND', 'LEAVES', 'HEAVY_TRAFFIC', 'ACCIDENT', 'POLICE', 'ROAD_CLOSURE', 'GAS_STATION', 'MOTO_SHOP', 'PARKING', 'SCENIC', 'CAFE', name='reporttype'),
               existing_nullable=False)
    op.alter_column('road_reports', 'severity',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='report_severity'),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='reportseverity'),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'::report_severity"))
    op.drop_index(op.f('idx_reports_active'), table_name='road_reports')
    op.drop_index(op.f('idx_reports_category'), table_name='road_reports')
    op.drop_index(op.f('idx_reports_expires'), table_name='road_reports')
    op.drop_index(op.f('idx_reports_type'), table_name='road_reports')
    op.drop_index(op.f('idx_route_history_created'), table_name='route_history')
    op.drop_index(op.f('idx_route_history_favorite'), table_name='route_history', postgresql_where='(is_favorite = true)')
    op.drop_index(op.f('idx_route_history_user'), table_name='route_history')
    op.create_index(op.f('ix_route_history_user_id'), 'route_history', ['user_id'], unique=False)
    op.drop_index(op.f('idx_user_badges_user'), table_name='user_badges')
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.drop_index(op.f('idx_user_challenges_user'), table_name='user_challenges')
    op.create_index(op.f('ix_user_challenges_user_id'), 'user_challenges', ['user_id'], unique=False)
    op.drop_index(op.f('idx_sessions_expires_at'), table_name='user_sessions')
    op.drop_index(op.f('idx_sessions_refresh_token'), table_name='user_sessions')
    op.drop_index(op.f('idx_sessions_user_id'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('idx_users_city'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_city'), 'users', ['city'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_city'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_city'), 'users', ['city'], unique=False)
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'google_id')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.create_index(op.f('idx_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_sessions_refresh_token'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('idx_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_user_challenges_user_id'), table_name='user_challenges')
    op.create_index(op.f('idx_user_challenges_user'), 'user_challenges', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.create_index(op.f('idx_user_badges_user'), 'user_badges', ['user_id'], unique=False)
    op.drop_index(op.f('ix_route_history_user_id'), table_name='route_history')
    op.create_index(op.f('idx_route_history_user'), 'route_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_route_history_favorite'), 'route_history', ['user_id', 'is_favorite'], unique=False, postgresql_where='(is_favorite = true)')
    op.create_index(op.f('idx_route_history_created'), 'route_history', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_reports_type'), 'road_reports', ['type'], unique=False)
    op.create_index(op.f('idx_reports_expires'), 'road_reports', ['expires_at'], unique=False)
    op.create_index(op.f('idx_reports_category'), 'road_reports', ['category'], unique=False)
    op.create_index(op.f('idx_reports_active'), 'road_reports', ['is_active'], unique=False)
    op.alter_column('road_reports', 'severity',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='reportseverity'),
               type_=postgresql.ENUM('low', 'medium', 'high', 'critical', name='report_severity'),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'::report_severity"))
    op.alter_column('road_reports', 'type',
               existing_type=sa.Enum('OIL_SPILL', 'DEBRIS', 'POTHOLE', 'CONSTRUCTION', 'TRAFFIC_LIGHT', 'ELECTRICAL', 'WET', 'ICE', 'FOG', 'SAND', 'LEAVES', 'HEAVY_TRAFFIC', 'ACCIDENT', 'POLICE', 'ROAD_CLOSURE', 'GAS_STATION', 'MOTO_SHOP', 'PARKING', 'SCENIC', 'CAFE', name='reporttype'),
               type_=postgresql.ENUM('oil_spill', 'debris', 'pothole', 'construction', 'traffic_light', 'electrical', 'wet', 'ice', 'fog', 'sand', 'leaves', 'heavy_traffic', 'accident', 'police', 'road_closure', 'gas_station', 'moto_shop', 'parking', 'scenic', 'cafe', name='report_type'),
               existing_nullable=False)
    op.alter_column('road_reports', 'category',
               existing_type=sa.Enum('HAZARD', 'SURFACE', 'TRAFFIC', 'POI', name='reportcategory'),
               type_=postgresql.ENUM('hazard', 'surface', 'traffic', 'poi', name='report_category'),
               existing_nullable=False)
    op.drop_index(op.f('ix_report_votes_user_id'), table_name='report_votes')
    op.drop_index(op.f('ix_report_votes_report_id'), table_name='report_votes')
    op.create_index(op.f('idx_votes_user'), 'report_votes', ['user_id'], unique=False)
    op.create_index(op.f('idx_votes_report'), 'report_votes', ['report_id'], unique=False)
    op.drop_index(op.f('ix_push_tokens_user_id'), table_name='push_tokens')
    op.create_index(op.f('idx_push_tokens_user'), 'push_tokens', ['user_id', 'is_active'], unique=False)
    op.drop_index(op.f('ix_post_comments_post_id'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_parent_id'), table_name='post_comments')
    op.create_index(op.f('idx_comments_post'), 'post_comments', ['post_id'], unique=False)
    op.create_index(op.f('idx_comments_parent'), 'post_comments', ['parent_id'], unique=False)
    op.drop_index(op.f('ix_point_transactions_user_id'), table_name='point_transactions')
    op.create_index(op.f('idx_transactions_user'), 'point_transactions', ['user_id'], unique=False)
    op.create_index(op.f('idx_transactions_date'), 'point_transactions', ['created_at'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.create_index(op.f('idx_notifications_user'), 'notifications', ['user_id', 'is_read', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('BADGE_EARNED', 'LEVEL_UP', 'STREAK', 'CHALLENGE_COMPLETE', 'REPORT_VERIFIED', 'REPORT_NEAR_ROUTE', 'COMMUNITY_POST', 'COMMUNITY_REPLY', 'COMMUNITY_MENTION', 'HELP_REQUEST_NEARBY', 'SYSTEM', name='notificationtype'),
               type_=postgresql.ENUM('badge_earned', 'level_up', 'streak', 'challenge_complete', 'report_verified', 'report_near_route', 'community_post', 'community_reply', 'community_mention', 'help_request_nearby', 'system', name='notification_type'),
               existing_nullable=False)
    op.drop_index(op.f('ix_motorcycles_user_id'), table_name='motorcycles')
    op.drop_index(op.f('ix_motorcycles_brand'), table_name='motorcycles')
    op.create_index(op.f('idx_motorcycles_user_id'), 'motorcycles', ['user_id'], unique=False)
    op.create_index(op.f('idx_motorcycles_type'), 'motorcycles', ['type'], unique=False)
    op.create_index(op.f('idx_motorcycles_brand'), 'motorcycles', ['brand'], unique=False)
    op.alter_column('motorcycles', 'type',
               existing_type=sa.Enum('NAKED', 'SPORT', 'TOURING', 'ADVENTURE', 'CRUISER', 'SCOOTER', 'CLASSIC', 'DUAL_SPORT', 'ENDURO', 'SUPERMOTO', 'CAFE_RACER', 'BOBBER', name='motorcycletype'),
               type_=postgresql.ENUM('naked', 'sport', 'touring', 'adventure', 'cruiser', 'scooter', 'classic', 'dual_sport', 'enduro', 'supermoto', 'cafe_racer', 'bobber', name='motorcycle_type'),
               existing_nullable=False)
    op.drop_column('motorcycles', 'tire_type')
    op.drop_column('motorcycles', 'torque_nm')
    op.drop_column('motorcycles', 'weight_kg')
    op.drop_index(op.f('ix_community_posts_community_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_author_id'), table_name='community_posts')
    op.create_index(op.f('idx_posts_type'), 'community_posts', ['type'], unique=False)
    op.create_index(op.f('idx_posts_created'), 'community_posts', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_posts_community'), 'community_posts', ['community_id'], unique=False)
    op.create_index(op.f('idx_posts_author'), 'community_posts', ['author_id'], unique=False)
    op.alter_column('community_posts', 'type',
               existing_type=sa.Enum('DISCUSSION', 'QUESTION', 'HELP_REQUEST', 'HELP_OFFER', 'RIDE_INVITE', 'EVENT', 'PHOTO', 'ROUTE_SHARE', name='posttype'),
               type_=postgresql.ENUM('discussion', 'question', 'help_request', 'help_offer', 'ride_invite', 'event', 'photo', 'route_share', name='post_type'),
               existing_nullable=True,
               existing_server_default=sa.text("'discussion'::post_type"))
    op.drop_index(op.f('ix_community_memberships_user_id'), table_name='community_memberships')
    op.drop_index(op.f('ix_community_memberships_community_id'), table_name='community_memberships')
    op.create_index(op.f('idx_memberships_user'), 'community_memberships', ['user_id'], unique=False)
    op.create_index(op.f('idx_memberships_community'), 'community_memberships', ['community_id'], unique=False)
    op.alter_column('community_memberships', 'role',
               existing_type=sa.Enum('MEMBER', 'MODERATOR', 'ADMIN', 'OWNER', name='membershiprole'),
               type_=postgresql.ENUM('member', 'moderator', 'admin', 'owner', name='membership_role'),
               existing_nullable=True,
               existing_server_default=sa.text("'member'::membership_role"))
    op.drop_index(op.f('ix_communities_slug'), table_name='communities')
    op.create_index(op.f('idx_communities_type'), 'communities', ['type'], unique=False)
    op.create_index(op.f('idx_communities_slug'), 'communities', ['slug'], unique=False)
    op.create_index(op.f('idx_communities_brand'), 'communities', ['brand_name'], unique=False)
    op.create_unique_constraint(op.f('communities_slug_key'), 'communities', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('communities', 'type',
               existing_type=sa.Enum('BRAND', 'STYLE', 'REGION', 'INTEREST', 'EVENT', name='communitytype'),
               type_=postgresql.ENUM('brand', 'style', 'region', 'interest', 'event', name='community_type'),
               existing_nullable=False)
    op.create_table('leaderboard_cache',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calculated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('leaderboard_cache_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('leaderboard_cache_pkey')),
    sa.UniqueConstraint('period', 'category', 'user_id', name=op.f('leaderboard_cache_period_category_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_leaderboard_period'), 'leaderboard_cache', ['period', 'category', 'rank'], unique=False)
    # ### end Alembic commands ###
